### ISSUE TITLE
Composer install failed after fork

### ISSUE THREAD

**Issue by pensiero** [zendframework/zend-i18n#1] opened 2015-05-20 09:23 UTC
I have forked this module and run a composer install, but I received this errors:

```
  Problem 1
    - Installation request for zendframework/zend-cache == 2.4.9999999.9999999-dev -> satisfiable by zendframework/zend-cache[2.4.x-dev].
    - zendframework/zend-cache 2.4.x-dev requires zendframework/zend-serializer == 2.4.9999999.9999999-dev -> no matching package found.
  Problem 2
    - Installation request for zendframework/zend-view == 2.4.9999999.9999999-dev -> satisfiable by zendframework/zend-view[2.4.x-dev].
    - zendframework/zend-view 2.4.x-dev requires zendframework/zend-loader == 2.4.9999999.9999999-dev -> no matching package found.
```

**Comment by Ocramius** [comment] 2015-05-20 12:00
Dupe of zendframework/zf2#7537

**Comment by Xerkus** [comment] 2015-05-20 21:46
@Gamempire as temporary solution add `"version": "2.4.2",` to composer.json file

**Comment by weierophinney** [comment] 2015-05-20 21:48
@Gamempire you're clearly asking for a dev dependency at this point. Use a stable tag; we'll be updating the various components to define semantic versions for dependencies soon.

**Closed as completed by weierophinney** 2015-05-20 21:48 UTC

**Comment by pensiero** [comment] 2015-05-21 07:44
Thanks for your answers
